Repository SSOTARTUP/ADHD, pull requests merged in 2023-10, with the labels that each got.

#7 [Feat/#4] 온보딩 뷰(약물 추가 제외) UI 구현
  Hamsters/Hamsters.xcodeproj/project.pbxproj
  Hamsters/Hamsters/AgreementView.swift
  Hamsters/Hamsters/Assets.xcassets/HasterImages/Contents.json
  Hamsters/Hamsters/Assets.xcassets/HasterImages/HamsterV.imageset/Contents.json
  Hamsters/Hamsters/Assets.xcassets/HasterImages/HamsterV.imageset/HamsterV.png
  Hamsters/Hamsters/Assets.xcassets/HasterImages/HamsterV.imageset/HamsterV@2x.png
  Hamsters/Hamsters/Assets.xcassets/HasterImages/HamsterV.imageset/HamsterV@3x.png
  Hamsters/Hamsters/Extensions/View+.swift
  Hamsters/Hamsters/Scenes/Onboarding/Components/OnboardingBackButton.swift
  Hamsters/Hamsters/Scenes/Onboarding/Components/OnboardingNextButton.swift
  Hamsters/Hamsters/Scenes/Onboarding/Components/OnboardingProgressBar.swift
  Hamsters/Hamsters/Scenes/Onboarding/NicknameSetView.swift
  Hamsters/Hamsters/Scenes/Onboarding/OnboardingView.swift
  Hamsters/Hamsters/Scenes/Onboarding/SetupCompleteView.swift
  Hamsters/Hamsters/Scenes/Onboarding/SexSetView.swift
  Hamsters/Hamsters/Scenes/Onboarding/SmokingSetView.swift
  Hamsters/Hamsters/Scenes/StartView.swift
Labels: Feature

#9 [Feat/#8] 온보딩 UserDefaults 연결
  Hamsters/Hamsters.xcodeproj/project.pbxproj
  Hamsters/Hamsters/Models/Enums/SexClassification.swift
  Hamsters/Hamsters/Models/Enums/SmokingStatus.swift
  Hamsters/Hamsters/Models/Enums/UserDefaultsKey.swift
  Hamsters/Hamsters/Scenes/Onboarding/NicknameSetView.swift
  Hamsters/Hamsters/Scenes/Onboarding/OnboardingView.swift
  Hamsters/Hamsters/Scenes/Onboarding/SetupCompleteView.swift
  Hamsters/Hamsters/Scenes/Onboarding/SexSetView.swift
  Hamsters/Hamsters/Scenes/Onboarding/SmokingSetView.swift
  Hamsters/Hamsters/Scenes/Onboarding/TempMedicationVeiw.swift
Labels: Feature

#13 [Design/#12] SE3 기기 대응
  Hamsters/Hamsters/AgreementView.swift
  Hamsters/Hamsters/Scenes/Onboarding/SetupCompleteView.swift
Labels: Design

#15 [Feat/#14] 데일리 기록(컨디션, 기분) 페이지 UI
  Hamsters/Hamsters.xcodeproj/project.pbxproj
  Hamsters/Hamsters.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Hamsters/Hamsters/Assets.xcassets/HasterImages/ConditionStatus/Contents.json
  Hamsters/Hamsters/Assets.xcassets/HasterImages/ConditionStatus/MyStatus0.imageset/Contents.json
  Hamsters/Hamsters/Assets.xcassets/HasterImages/ConditionStatus/MyStatus0.imageset/MyStatus0.png
  Hamsters/Hamsters/Assets.xcassets/HasterImages/ConditionStatus/MyStatus0.imageset/MyStatus0@2x.png
  Hamsters/Hamsters/Assets.xcassets/HasterImages/ConditionStatus/MyStatus0.imageset/MyStatus0@3x.png
  Hamsters/Hamsters/Assets.xcassets/HasterImages/ConditionStatus/MyStatus1.imageset/Contents.json
  Hamsters/Hamsters/Assets.xcassets/HasterImages/ConditionStatus/MyStatus1.imageset/MyStatus1.png
  Hamsters/Hamsters/Assets.xcassets/HasterImages/ConditionStatus/MyStatus1.imageset/MyStatus1@2x.png
  Hamsters/Hamsters/Assets.xcassets/HasterImages/ConditionStatus/MyStatus1.imageset/MyStatus1@3x.png
  Hamsters/Hamsters/Assets.xcassets/HasterImages/ConditionStatus/MyStatus2.imageset/Contents.json
  Hamsters/Hamsters/Assets.xcassets/HasterImages/ConditionStatus/MyStatus2.imageset/MyStatus2.png
  Hamsters/Hamsters/Assets.xcassets/HasterImages/ConditionStatus/MyStatus2.imageset/MyStatus2@2x.png
  Hamsters/Hamsters/Assets.xcassets/HasterImages/ConditionStatus/MyStatus2.imageset/MyStatus2@3x.png
  Hamsters/Hamsters/Assets.xcassets/HasterImages/ConditionStatus/MyStatus3.imageset/Contents.json
  Hamsters/Hamsters/Assets.xcassets/HasterImages/ConditionStatus/MyStatus3.imageset/MyStatus3.png
  Hamsters/Hamsters/Assets.xcassets/HasterImages/ConditionStatus/MyStatus3.imageset/MyStatus3@2x.png
  Hamsters/Hamsters/Assets.xcassets/HasterImages/ConditionStatus/MyStatus3.imageset/MyStatus3@3x.png
  Hamsters/Hamsters/Assets.xcassets/HasterImages/ConditionStatus/MyStatus4.imageset/Contents.json
  Hamsters/Hamsters/Assets.xcassets/HasterImages/ConditionStatus/MyStatus4.imageset/MyStatus4.png
  Hamsters/Hamsters/Assets.xcassets/HasterImages/ConditionStatus/MyStatus4.imageset/MyStatus4@2x.png
  Hamsters/Hamsters/Assets.xcassets/HasterImages/ConditionStatus/MyStatus4.imageset/MyStatus4@3x.png
  Hamsters/Hamsters/Scenes/DailyRecord/Components/ConditionSlider.swift
  Hamsters/Hamsters/Scenes/DailyRecord/Components/DailyRecordNextButton.swift
  Hamsters/Hamsters/Scenes/DailyRecord/Components/DailyRecordProgressBar.swift
  Hamsters/Hamsters/Scenes/DailyRecord/ConditionCheckView.swift
  Hamsters/Hamsters/Scenes/DailyRecord/DailyRecordView.swift
  Hamsters/Hamsters/Scenes/DailyRecord/MoodCheckView.swift
Labels: Feature

#20 [Setting/#19] TestFlight 위한 설정 변경
  Hamsters/Hamsters.xcodeproj/project.pbxproj
  Hamsters/Hamsters/Assets.xcassets/AppIcon.appiconset/ClueLogo.png
  Hamsters/Hamsters/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: Setting

#23 [Feat/#22] 데일리 기록(메모, 완료) 페이지 UI
  Hamsters/Hamsters.xcodeproj/project.pbxproj
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/AdditionalMemoView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/Components/DailyRecordNextButton.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/Components/DailyRecordProgressBar.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/ConditionCheckView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/DailyCompleteView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/DailyRecordView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/MoodCheckView.swift
Labels: Feature

#24 [Feat/#21] 부작용 기록 UI 구현
  Hamsters/Hamsters.xcodeproj/project.pbxproj
  Hamsters/Hamsters.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Hamsters/Hamsters/Models/Enums/SideEffects.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/Components/CapsuleView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/SideEffectCheckView.swift
Labels: Feature

#27 [Feat/#25] 체중 기록, 월경 여부 UI 구현
  Hamsters/Hamsters.xcodeproj/project.pbxproj
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/MenstruationCheckView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/SideEffectCheckView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/WeightCheckView.swift
Labels: Feature

#30 [Ryu_Feat/#29] 수면 기록 뷰 구현
  Hamsters/Hamsters.xcodeproj/project.pbxproj
  Hamsters/Hamsters/Extensions/View+.swift
  Hamsters/Hamsters/Models/Medicine/MedicineModel.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/SleepingTimeView.swift
Labels: Feature

#33 [Chore] DailyRecordView 추가 화면 연결, 버튼 여백 수정
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/DailyRecordView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/MenstruationCheckView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/SideEffectCheckView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/SleepingTimeView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/WeightCheckView.swift
Labels: Chore

#34 [Design/#31] 디자인 디테일 수정
  Hamsters/Hamsters.xcodeproj/project.pbxproj
  Hamsters/Hamsters/AgreementView.swift
  Hamsters/Hamsters/Assets.xcassets/HasterImages/HamLogo.imageset/Contents.json
  Hamsters/Hamsters/Assets.xcassets/HasterImages/HamLogo.imageset/LOGO.png
  Hamsters/Hamsters/Scenes/Onboarding/Medication/MedicationView.swift
  Hamsters/Hamsters/Scenes/Onboarding/OnboardingView.swift
  Hamsters/Hamsters/Scenes/Onboarding/SetupCompleteView.swift
  Hamsters/Hamsters/Scenes/Tab/DiaryTab/DiaryMainView.swift
  Hamsters/Hamsters/Scenes/Tab/MyInfoTab/MyInfoMainView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyMedicationList.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/AdditionalMemoView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/Components/DailyRecordNextButton.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/ConditionCheckView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/DailyCompleteView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/DailyRecordView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/MenstruationCheckView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/MoodCheckView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/SideEffectCheckView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/SleepingTimeView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/WeightCheckView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/RecordMainView.swift
  Hamsters/Hamsters/Scenes/Tab/StatisticsTab/StatisticsMainView.swift
Labels: Design
