Repository SSOTARTUP/ADHD, pull requests merged in 2023-11, with the labels that each got.

#37 [Chore] 브랜치 최신화
  Hamsters/Hamsters/Models/Medicine/MedicineModel.swift
  Hamsters/Hamsters/Scenes/Onboarding/Medication/MedicationView.swift
  Hamsters/Hamsters/Scenes/Onboarding/OnboardingView.swift
  Hamsters/Hamsters/Scenes/Onboarding/SetupCompleteView.swift
  Hamsters/Hamsters/Scenes/StartView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/SideEffectCheckView.swift
Labels: Chore

#43 [Feat/#38] 온보딩 디테일 수정(성별, 흡연)
  Hamsters/Hamsters.xcodeproj/project.pbxproj
  Hamsters/Hamsters/Scenes/Onboarding/Components/ProgressBarAndTitle.swift
  Hamsters/Hamsters/Scenes/Onboarding/SexSetView.swift
  Hamsters/Hamsters/Scenes/Onboarding/SmokingSetView.swift
Labels: Feature

#59 [Feat/#36] 투여약 관련 뷰 수정 및 데이터 편집 구현
  Hamsters/Hamsters/Models/Medicine/AlarmItem.swift
  Hamsters/Hamsters/Models/Medicine/MedicineModel.swift
  Hamsters/Hamsters/Scenes/Onboarding/Medication/AddMedicineView.swift
  Hamsters/Hamsters/Scenes/Onboarding/Medication/AlarmFrequencyView.swift
  Hamsters/Hamsters/Scenes/Onboarding/Medication/MedicationView.swift
  Hamsters/Hamsters/Scenes/Onboarding/Medication/MedicineRow.swift
  Hamsters/Hamsters/Scenes/Onboarding/ViewModel/AlarmViewModel.swift
  Hamsters/Hamsters/Scenes/Onboarding/ViewModel/MedicineViewModel.swift
Labels: Feature

#60 [Feat/#53] 온보딩 상세뷰 연결
  Hamsters/Hamsters.xcodeproj/project.pbxproj
  Hamsters/Hamsters.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Hamsters/Hamsters.xcodeproj/xcshareddata/xcschemes/Hamsters.xcscheme
  Hamsters/Hamsters/AgreementView.swift
  Hamsters/Hamsters/Models/Enums/Onboarding.swift
  Hamsters/Hamsters/Models/Enums/UserDefaultsKey.swift
  Hamsters/Hamsters/Scenes/Onboarding/Components/OnboardingBackButton.swift
  Hamsters/Hamsters/Scenes/Onboarding/Components/OnboardingNextButton.swift
  Hamsters/Hamsters/Scenes/Onboarding/Components/OnboardingProgressBar.swift
  Hamsters/Hamsters/Scenes/Onboarding/Components/ProgressBarAndTitle.swift
  Hamsters/Hamsters/Scenes/Onboarding/Medication/MedicationView.swift
  Hamsters/Hamsters/Scenes/Onboarding/NicknameSetView.swift
  Hamsters/Hamsters/Scenes/Onboarding/OnboardingView.swift
  Hamsters/Hamsters/Scenes/Onboarding/ProfileSetView.swift
  Hamsters/Hamsters/Scenes/Onboarding/SetupCompleteView.swift
  Hamsters/Hamsters/Scenes/Onboarding/SexSetView.swift
  Hamsters/Hamsters/Scenes/Onboarding/SmokingSetView.swift
  Hamsters/Hamsters/Scenes/Onboarding/WelcomeView.swift
  Hamsters/Hamsters/Scenes/StartView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/Components/NextButton.swift
Labels: Feature

#62 [Feat/#61] 기록뷰(격려 페이지, 기타 메모, 기록 완료) 구현
  Hamsters/Hamsters.xcodeproj/project.pbxproj
  Hamsters/Hamsters/Scenes/Onboarding/Components/OnboardingProgressBar.swift
  Hamsters/Hamsters/Scenes/Onboarding/LottieConfettiView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/AdditionalMemoView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/CheerUpView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/Components/DailyRecordNextButton.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/DailyCompleteView.swift
Labels: Feature

#66 [Feat/#63] 기록뷰(흡연, 카페인, 음주) 구현
  Hamsters/Hamsters/Models/Enums/DrinkAmount.swift
  Hamsters/Hamsters/Models/Enums/SmokingAmount.swift
  Hamsters/Hamsters/Resource/Assets.xcassets/CaffeineImages/CaffeineSelected.imageset/CaffeineSelected.png
  Hamsters/Hamsters/Resource/Assets.xcassets/CaffeineImages/CaffeineSelected.imageset/CaffeineSelected@2x.png
  Hamsters/Hamsters/Resource/Assets.xcassets/CaffeineImages/CaffeineSelected.imageset/CaffeineSelected@3x.png
  Hamsters/Hamsters/Scenes/Onboarding/OnboardingView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/AdditionalMemoView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/CaffeineCheckView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/DailyRecordView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/DrinkCheckView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/SmokingCheckView.swift
Labels: Feature

#77 [Feat/#35] 투여 기록 데이터 저장 및 CoreData
  Hamsters/CoreDataManager.swift
  Hamsters/CoreMedicineModel.xcdatamodeld/CoreMedicineModel.xcdatamodel/contents
  Hamsters/Hamsters.xcodeproj/project.pbxproj
  Hamsters/Hamsters/Models/Medicine/AlarmItem.swift
  Hamsters/Hamsters/Scenes/Onboarding/Medication/MedicationView.swift
  Hamsters/Hamsters/Scenes/Onboarding/ViewModel/MedicineViewModel.swift
  Hamsters/Medicines+CoreDataClass.swift
  Hamsters/Medicines+CoreDataProperties.swift
Labels: Feature

#80 [Feat/#78]부작용 기록 UI 변경 및 기능 구현
  Hamsters/Hamsters/Models/Enums/SideEffects.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/Components/CapsuleView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/DailyRecordView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/SideEffectCheckView.swift
Labels: Feature

#84 [Design/#81] 수면 기록 UI 변경 및 SE 대응
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/SleepingTimeView.swift
Labels: Design

#86 [Design/#85] 체중 기록 UI 변경
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/DailyRecordView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/WeightCheckView.swift
Labels: Design

#87 [Design/#81] Scroll 추가
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/SleepingTimeView.swift
Labels: Design

#88 [Fix] 부작용 선택 시 없음 선택해제 버그 수정
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/SideEffectCheckView.swift
Labels: Fix

#96 [Feat/#92] 기록하기 메인뷰 UI 임시 구현
  Hamsters/Hamsters.xcodeproj/project.pbxproj
  Hamsters/Hamsters/Extensions/Date.swift
  Hamsters/Hamsters/Models/Medicine/MedicineModel.swift
  Hamsters/Hamsters/Resource/Assets.xcassets/HasterImages/goldenHamster.imageset/Contents.json
  Hamsters/Hamsters/Resource/Assets.xcassets/HasterImages/goldenHamster.imageset/goldenHamster.png
  Hamsters/Hamsters/Resource/Assets.xcassets/HasterImages/goldenHamster.imageset/goldenHamster@2x.png
  Hamsters/Hamsters/Resource/Assets.xcassets/HasterImages/goldenHamster.imageset/goldenHamster@3x.png
  Hamsters/Hamsters/Resource/Assets.xcassets/RecordMainGraphic/Cloud.imageset/Cloud.png
  Hamsters/Hamsters/Resource/Assets.xcassets/RecordMainGraphic/Cloud.imageset/Cloud@2x.png
  Hamsters/Hamsters/Resource/Assets.xcassets/RecordMainGraphic/Cloud.imageset/Cloud@3x.png
  Hamsters/Hamsters/Resource/Assets.xcassets/RecordMainGraphic/Cloud.imageset/Contents.json
  Hamsters/Hamsters/Resource/Assets.xcassets/RecordMainGraphic/Contents.json
  Hamsters/Hamsters/Resource/Assets.xcassets/RecordMainGraphic/GroundColor.colorset/Contents.json
  Hamsters/Hamsters/Resource/Assets.xcassets/RecordMainGraphic/Mound.imageset/Contents.json
  Hamsters/Hamsters/Resource/Assets.xcassets/RecordMainGraphic/Mound.imageset/Mound.png
  Hamsters/Hamsters/Resource/Assets.xcassets/RecordMainGraphic/Mound.imageset/Mound@2x.png
  Hamsters/Hamsters/Resource/Assets.xcassets/RecordMainGraphic/Mound.imageset/Mound@3x.png
  Hamsters/Hamsters/Resource/Assets.xcassets/RecordMainGraphic/SkyColor.colorset/Contents.json
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyMedicationList.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/RecordMainView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/RecordWeeklyCalendar.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/WeeklyMedicationCalendar.swift
Labels: Feature

#99 Ryu feat/#90
  Hamsters/CoreDataManager.swift
  Hamsters/CoreDataModel.xcdatamodeld/CoreMedicineModel.xcdatamodel/contents
  Hamsters/CoreMedicineModel.xcdatamodeld/CoreMedicineModel.xcdatamodel/contents
  Hamsters/DayRecords+CoreDataClass.swift
  Hamsters/DayRecords+CoreDataProperties.swift
  Hamsters/Hamsters.xcodeproj/project.pbxproj
  Hamsters/Hamsters/Models/Enums/SideEffects.swift
  Hamsters/Hamsters/Models/Record/DailyViewModel.swift
  Hamsters/Hamsters/Models/Record/DayRecord.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/Components/DailyRecordNextButton.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/DailyCompleteView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/DailyRecordView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/SleepingTimeView.swift
Labels: Feature

#103 [Feat] 내 정보(설정) 페이지 구현
  Hamsters/Hamsters.xcodeproj/project.pbxproj
  Hamsters/Hamsters/HamstersApp.swift
  Hamsters/Hamsters/Models/Enums/SelectedHamster.swift
  Hamsters/Hamsters/Models/Enums/UserDefaultsKey.swift
  Hamsters/Hamsters/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  Hamsters/Hamsters/Scenes/Onboarding/OnboardingView.swift
  Hamsters/Hamsters/Scenes/Onboarding/ProfileSetView.swift
  Hamsters/Hamsters/Scenes/Tab/MyInfoTab/MyInfoMainView.swift
  Hamsters/Hamsters/Scenes/Tab/MyInfoTab/MyInfoViewModel.swift
  Hamsters/Hamsters/Scenes/Tab/MyInfoTab/ProfileEditView.swift
  Hamsters/Hamsters/Scenes/Tab/MyInfoTab/QuestionItemEditView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/RecordMainView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/RecordWeeklyCalendar.swift
Labels: Feature

#107 [Feat/#90] 복용여부 takenMedicines 모델 및 Coredata 생성
  Hamsters/CoreDataModel.xcdatamodeld/CoreMedicineModel.xcdatamodel/contents
  Hamsters/Hamsters.xcodeproj/project.pbxproj
  Hamsters/Hamsters/Models/Medicine/MedicineModel.swift
  Hamsters/Hamsters/Models/Record/DailyMedicationViewModel.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/MainTabView.swift
  Hamsters/TakenMedicine+CoreDataClass.swift
  Hamsters/TakenMedicine+CoreDataProperties.swift
  Hamsters/TakenMedicines+CoreDataClass.swift
  Hamsters/TakenMedicines+CoreDataProperties.swift
Labels: Feature

#124 [Feat/#123] 기록하기 메인뷰 복약 체크 데이터 연결
  Hamsters/Hamsters.xcodeproj/project.pbxproj
  Hamsters/Hamsters/Models/Manager/TakensManager.swift
  Hamsters/Hamsters/Scenes/Tab/MainTabView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyMedicationList.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/RecordMainView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/viewModel/RecordMainViewModel.swift
Labels: Feature

#125 Ryu feat/#108
  Hamsters/Hamsters/Resource/Assets.xcassets/ThoColors/THO_Orange.colorset/Contents.json
  Hamsters/Hamsters/Scenes/Tab/DiaryTab/DiaryMainView.swift
Labels: Feature

#130 [Feat/#105] 기록하기 메인뷰 캘린더 데이터-UI 연동
  Hamsters/Hamsters/Extensions/Date.swift
  Hamsters/Hamsters/Extensions/String+.swift
  Hamsters/Hamsters/Models/Enums/UserDefaultsKey.swift
  Hamsters/Hamsters/Scenes/Onboarding/ViewModel/OnboardingViewModel.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/RecordMainView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/RecordWeeklyCalendar.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/viewModel/RecordMainViewModel.swift
Labels: Feature

#132 [Design/#131]
  Hamsters/Hamsters.xcodeproj/project.pbxproj
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/ActivityView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/CaffeineCheckView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/CheerUpView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/Components/DailyRecordNextTwoButtons.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/ConditionCheckView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/ConditionView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/DrinkCheckView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/MenstruationCheckView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/MoodCheckView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/SideEffectCheckView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/SleepingTimeView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/SmokingCheckView.swift
Labels: Design

#135 [Feat/#134] 기록하기 버튼 disable 기능 확인
  Hamsters/Hamsters/Scenes/Tab/RecordTab/RecordMainView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/viewModel/RecordMainViewModel.swift
Labels: Feature

#139 [Feat/#119] 온보딩 UI 디테일 정리
  Hamsters/Hamsters/Models/Enums/Onboarding.swift
  Hamsters/Hamsters/Resource/Assets.xcassets/HasterImages/OnboardinWelcome/Contents.json
  Hamsters/Hamsters/Resource/Assets.xcassets/HasterImages/OnboardinWelcome/Welcome1.imageset/Contents.json
  Hamsters/Hamsters/Resource/Assets.xcassets/HasterImages/OnboardinWelcome/Welcome1.imageset/Welcome1.png
  Hamsters/Hamsters/Resource/Assets.xcassets/HasterImages/OnboardinWelcome/Welcome1.imageset/Welcome1@2x.png
  Hamsters/Hamsters/Resource/Assets.xcassets/HasterImages/OnboardinWelcome/Welcome1.imageset/Welcome1@3x.png
  Hamsters/Hamsters/Resource/Assets.xcassets/HasterImages/OnboardinWelcome/Welcome2.imageset/Contents.json
  Hamsters/Hamsters/Resource/Assets.xcassets/HasterImages/OnboardinWelcome/Welcome2.imageset/Welcome2.png
  Hamsters/Hamsters/Resource/Assets.xcassets/HasterImages/OnboardinWelcome/Welcome2.imageset/Welcome2@2x.png
  Hamsters/Hamsters/Resource/Assets.xcassets/HasterImages/OnboardinWelcome/Welcome2.imageset/Welcome2@3x.png
  Hamsters/Hamsters/Resource/Assets.xcassets/HasterImages/OnboardinWelcome/Welcome3.imageset/Contents.json
  Hamsters/Hamsters/Resource/Assets.xcassets/HasterImages/OnboardinWelcome/Welcome3.imageset/Welcome3.png
  Hamsters/Hamsters/Resource/Assets.xcassets/HasterImages/OnboardinWelcome/Welcome3.imageset/Welcome3@2x.png
  Hamsters/Hamsters/Resource/Assets.xcassets/HasterImages/OnboardinWelcome/Welcome3.imageset/Welcome3@3x.png
  Hamsters/Hamsters/Resource/onboardingConfetti.json
  Hamsters/Hamsters/Scenes/Onboarding/OnboardingView.swift
  Hamsters/Hamsters/Scenes/Onboarding/SetupCompleteView.swift
  Hamsters/Hamsters/Scenes/Onboarding/WelcomeView.swift
Labels: Design

#140 [Feat/#138] Edit page
  Hamsters/Hamsters.xcodeproj/project.pbxproj
  Hamsters/Hamsters/HamstersApp.swift
  Hamsters/Hamsters/Models/Manager/DayRecordsManager.swift
  Hamsters/Hamsters/Models/Manager/MedicinesManager.swift
  Hamsters/Hamsters/Scenes/Onboarding/Medication/AddMedicineView.swift
  Hamsters/Hamsters/Scenes/Tab/DiaryTab/DiaryMainView.swift
  Hamsters/Hamsters/Scenes/Tab/DiaryTab/viewModel/DiaryMainViewModel.swift
  Hamsters/Hamsters/Scenes/Tab/MyInfoTab/EditMedicineView.swift
  Hamsters/Hamsters/Scenes/Tab/MyInfoTab/MyInfoMainView.swift
Labels: Feature

#145 [Feat/#141] 다이어리탭 캘린더 UI 적용
  Hamsters/Hamsters.xcodeproj/project.pbxproj
  Hamsters/Hamsters/Scenes/Tab/DiaryTab/DiaryContentsView.swift
  Hamsters/Hamsters/Scenes/Tab/DiaryTab/DiaryExpandedCalendarView.swift
  Hamsters/Hamsters/Scenes/Tab/DiaryTab/DiaryMainView.swift
  Hamsters/Hamsters/Scenes/Tab/DiaryTab/DiaryMonthlyCalendar.swift
  Hamsters/Hamsters/Scenes/Tab/DiaryTab/DiaryTempWeeklyView.swift
  Hamsters/Hamsters/Scenes/Tab/DiaryTab/DiaryWeeklyCalendar.swift
  Hamsters/Hamsters/Scenes/Tab/DiaryTab/viewModel/DiaryCalendarViewModel.swift
  Hamsters/Hamsters/Scenes/Tab/DiaryTab/viewModel/DiaryMainViewModel.swift
Labels: Feature

#147 [Feat/#143] 약물 및 흡연 범위 조절 및 예외 처리
  Hamsters/Hamsters/Models/Enums/DrinkAmount.swift
  Hamsters/Hamsters/Models/Enums/SmokingAmount.swift
  Hamsters/Hamsters/Scenes/Tab/DiaryTab/DiaryMainView.swift
Labels: Feature

#154 [Fix] 다이어리 충돌 파일 수정
  Hamsters/Hamsters/Models/Enums/DrinkAmount.swift
  Hamsters/Hamsters/Models/Enums/SmokingAmount.swift
  Hamsters/Hamsters/Scenes/Tab/DiaryTab/DiaryContentsView.swift
Labels: Fix

#156 [Feat/#155] DiaryContentsView 복용 약물 연동 및 완성
  Hamsters/Hamsters/Scenes/Tab/DiaryTab/DiaryContentsView.swift
Labels: Feature

#159 [Design/#142] 햄스터 애니메이션 적용
  Hamsters/Hamsters.xcodeproj/project.pbxproj
  Hamsters/Hamsters/Models/Enums/SelectedHamster.swift
  Hamsters/Hamsters/Resource/CheerUpHamster/Middle_Ham1.json
  Hamsters/Hamsters/Resource/CheerUpHamster/Middle_Ham2.json
  Hamsters/Hamsters/Resource/CheerUpHamster/Middle_Ham3.json
  Hamsters/Hamsters/Resource/OnboardingFinishHamster/OnBoardingFin.json
  Hamsters/Hamsters/Resource/RecordFinishHamster/RecordFin_Ham1.json
  Hamsters/Hamsters/Resource/RecordFinishHamster/RecordFin_Ham2.json
  Hamsters/Hamsters/Resource/RecordFinishHamster/RecordFin_Ham3.json
  Hamsters/Hamsters/Resource/RecordMainHamster/Main_Ham1_After.json
  Hamsters/Hamsters/Resource/RecordMainHamster/Main_Ham1_Before.json
  Hamsters/Hamsters/Resource/RecordMainHamster/Main_Ham2_After.json
  Hamsters/Hamsters/Resource/RecordMainHamster/Main_Ham2_Before.json
  Hamsters/Hamsters/Resource/RecordMainHamster/Main_Ham3_After.json
  Hamsters/Hamsters/Resource/RecordMainHamster/Main_Ham3_Before.json
  Hamsters/Hamsters/Resource/onboardingConfetti.json
  Hamsters/Hamsters/Scenes/Onboarding/SetupCompleteView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/CheerUpView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/DailyCompleteView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/RecordMainView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/viewModel/RecordMainViewModel.swift
Labels: Design

#161 [Feat/#160] 기록있는 날짜 불러오기 및 캘린더 연동
  Hamsters/Hamsters/Scenes/Tab/DiaryTab/DiaryExpandedCalendarView.swift
  Hamsters/Hamsters/Scenes/Tab/DiaryTab/DiaryMainView.swift
  Hamsters/Hamsters/Scenes/Tab/DiaryTab/DiaryMonthlyCalendar.swift
  Hamsters/Hamsters/Scenes/Tab/DiaryTab/DiaryWeeklyCalendar.swift
  Hamsters/Hamsters/Scenes/Tab/DiaryTab/viewModel/DiaryMainViewModel.swift
Labels: Feature

#163 Ryu feat/#158
  Hamsters/Hamsters/Models/Manager/HealthKitManager.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/SleepingTimeView.swift
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyRecord/ViewModel/DailyRecordViewModel.swift
Labels: Feature

#164 [Feat/#162] 약물 빈도가 필요시 일 때 UI 반영
  Hamsters/Hamsters/Scenes/Tab/RecordTab/DailyMedicationList.swift
Labels: Feature
